#+TITLE: Doom Docs

Getting to know Doom for ii spacemacs users.
* Doom Basics
Doom is, like Spacemacs, a /flavour/ of Emacs.  It is still Emacs underneath it all, but with some pre-configured set of packages, UI, and keybindings.

It is designed to be simple (as simple as Emacs can be!), fast, and orderly to maintain.
* Differences to Spacemacs
Doom works with a paradigm of "Projects" that is more deeply integrated than Spacemacs.  Each repo you work in is its own project, with its own set of TODO's, buffers, and file exploration.
(This is done, partly, in Spacemacs but the integration is not as consistent or smooth.)  A number of the basic keybindings in Doom are to help with the project setup. Notably:

** ~SPC SPC~ does not map to M-x, use ~SPC :~ instead
~SPC SPC~ is now a project file switcher, which lets you quickly navigate your project repo.
** ~SPC gg~ brings up git dispatch (instead of SPC gs)
The rest of magit works the same (mostly), it's just the way you reach the dispatch
** ~,,~ navigates open org files
This affects your org src blocks and any confirm commands (like confirming your git commit message)
Now, *to execute src blocks use ~gr~* and *to confirm use C-c C-c*
* Configuring Doom
If you've made changes to yoru config, they will not apply automatically, especially if you've toggled a new package.  Doom
* Getting Help
There's great internal documentation that can help to learn the new keybindings, along with all the cool tools available to you.
 - SPC h :: brings up the help docs
 - SPC h f :: describe function
 - SPC h v :: describe variable
 - SPC h d h :: doom help manual (the readme on doom's github)
 - SPC h d m :: module help (e.g. seeing what's avaialble for go-mode)
* Resources
In addition, I recommend these resources:
+ [[https://github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org][Official Getting Started Guide]]
+ [[https://www.youtube.com/watch?v=rCMh7srOqvw&list=PLhXZp00uXBk4np17N39WvB80zgxlZfVwj][Zaiste's Doom Emacs Series]]
